In [ ]:
# Introducation on Numpy------>
# Numpy is an open -source librrary that is used for handle scintic calculations.
# Difference between list and Numpy----->

#(1). List hetrogeneous data type and Numpy is Homogeneous data type.
#(2). List take morw memory as compare to numpy.
#(3). list take more excuation time as compare to NUmpy

In [ ]:
# pip install numpy---> for vs code
# !pip install numpy ---> for jupter notebook.
# uv add -r requirements.txt ---> for uv in vs code.

In [ ]:
import numpy as np

In [ ]:
a = [1,45,78,90]
type(a)

list

In [ ]:
b=np.array(a)
b
type(b)


numpy.ndarray

In [ ]:
# user defined array

In [ ]:
a=[]
size =int(input("Enter the size :"))
for i in range(size):
  val =int(input("enter item :"))
  a.append(val)
# print(a)
b=np.array(a)
b

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Matrix ----> rowa,columns

# row_1 =[1,2,3]
# row_2 =[4,5,6]
# row_3 =[7,8,9]

# total elements =row*col 3*3 = 9


In [ ]:
print("total row and column: ",b.shape)
print("total elements: ",b.size)

total row and column:  (3, 3)
total elements:  9


In [ ]:
a=[[1,2,3,4],[6,5,6,7],[4,6,7,8,]]
b=np.array(a)
b

array([[1, 2, 3, 4],
       [6, 5, 6, 7],
       [4, 6, 7, 8]])

In [ ]:
print("total row and column: ",b.shape)
print("total elements: ",b.size)

total row and column:  (3, 4)
total elements:  12


In [ ]:
# how to check dimension or an matrix

In [ ]:
a=np.array([1,3,4])
a

array([1, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a=np.array([[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a.ndim

3

In [ ]:
# images -----> Pixels(0-255) ---> Normalize(0-1)--->matrix --->operations
# DL ---->Artifical neurons --> weight---> randomly cretaion -->Numpy
# datasets --->Dummy entry --->random module ---> attach pandas

In [ ]:
# pre -defined functions in Numpy

In [ ]:
# (1). zeros() ---> it will crete an array in which all the values will be zero in wither 1 -D or
# multi-dimensional

In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# a.shape

In [ ]:
# (2). one() ---> it will crete an array which all the values will be 1 in wither 1-D or
#multi-dimensional

In [ ]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [ ]:
a=np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# (3). eye()--> it will crete an arry in which digonal positional elements will be in either
# 1 and rest all are o

In [ ]:
a= np.eye(3)  # row = column ---> symentric marks
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# (4). diag() ---> it will crete an array in which we can set our custom values at
# digonal position


In [ ]:
a=np.diag([1,37,72,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 37,  0,  0],
       [ 0,  0, 72,  0],
       [ 0,  0,  0, 90]])

In [ ]:
# (5). Random module--->
# (a).Randit() ---> it will crete an array randomly ina given range
# syntax: np.random.randint(min_value,max_value,total_values)

In [ ]:
a=np.random.randint(1,10,3)
a

array([8, 3, 4])

In [ ]:
# (b). rand() ---> it will fix or lock our genrated data
# syntax : np.random.rand(total_random_number)


In [ ]:
a=np.random.rand(5)
a

array([0.65292733, 0.44676874, 0.27834134, 0.4760083 , 0.93831945])

In [ ]:
# (c).
# dataset(emp_data)(emp_id,salary,domain)---> randomly column add (working hours)

In [ ]:
# (c) .seed() ---> it will fix or lock genrated data.
# syantax:
# np.random.seed(45)
a=np.random.randint(1,10,3)
a

array([8, 9, 3])

In [ ]:
np.random.seed(45)
a=np.random.randint(1,10,3)
a

array([4, 1, 6])

In [ ]:
# view vs Copy


In [ ]:
a= np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
b=a[1:4]
b[:]=0
b

array([0, 0, 0])

In [ ]:
a

array([10,  0,  0,  0, 50, 60, 70, 80])

In [ ]:
#copy
a=np.array([10, 20, 30, 40, 50, 60, 70, 80])
b=a[1:4].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [ ]:
#Reshaping the array
# total row*columns=total_elemnents

In [ ]:
a=np.random.randint(1,50,12)
a

array([ 1, 31,  1, 34, 28,  5, 16, 40, 14, 49, 22, 31])

In [ ]:
# 1*12 ,12*1
# 2*6 ,6*2
# 3*4, 4*3


In [ ]:
a.reshape(2,6)


array([[ 1, 31,  1, 34, 28,  5],
       [16, 40, 14, 49, 22, 31]])

In [ ]:
a.reshape(3,4)


array([[ 1, 31,  1, 34],
       [28,  5, 16, 40],
       [14, 49, 22, 31]])

In [ ]:
a.reshape(1,12)


array([[ 1, 31,  1, 34, 28,  5, 16, 40, 14, 49, 22, 31]])

In [ ]:
a.shape

(12,)

In [ ]:
a.reshape(-1,3)

array([[ 1, 31,  1],
       [34, 28,  5],
       [16, 40, 14],
       [49, 22, 31]])

In [ ]:
a.reshape(2,-1)


array([[16, 18,  7, 45, 43, 12],
       [41,  9, 14, 12, 43, 17]])

In [ ]:
# operation on array
# arange ---> it genrate number like range
# reshape---> it give matrix to array

In [ ]:
a=np.arange(1,5,2)
a

array([1, 3])

In [ ]:
a*2


array([2, 6])

In [ ]:
a**3

array([ 1, 27])

In [ ]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [ ]:
a+b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a-b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a.dot(b) # this is for matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a>10


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [ ]:
b=[a>5]
b

[array([False,  True, False,  True,  True, False,  True,  True,  True,
         True,  True,  True])]

In [ ]:
b=np.arange(1,4)
b**2

array([1, 4, 9])

In [ ]:
a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(a)

np.int64(45)

In [ ]:
np.sum(a,axis=1) # axis 1 means row wise operation

array([ 6, 15, 24])

In [ ]:
np.sum(a,axis=0) # axis 0 means column wise operation

array([12, 15, 18])

In [ ]:
# unique()--> it will crete an array in which it will remove duplicate vales
# it will return 3 array
# arr-- > unique elements of array
# return_indes = true---> indexing of unique element
# return_counts =true ---> frequency of each unique element

In [ ]:
a=np.array([1,2,3,1,1,1,4,5,4,4,4,6,7])
a

array([1, 2, 3, 1, 1, 1, 4, 5, 4, 4, 4, 6, 7])

In [ ]:
b=np.unique(a,return_index=True,return_counts=True)

In [ ]:
b

(array([1, 2, 3, 4, 5, 6, 7]),
 array([ 0,  1,  2,  6,  7, 11, 12]),
 array([4, 1, 1, 4, 1, 1, 1]))

In [ ]:
# linspace()---> it will return an array in which elements will be same gap in a given range

In [ ]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Horizontal And Vertical Stacking ---- >
# Horizontal Stacking --- > It will add 2 or more arrays in horizontally .



In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
b= np.arange(5,9)
b

array([5, 6, 7, 8])

In [ ]:
c=np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [ ]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])